from .economy import (
    TrainClosingPackageGoal,
    RebuildCastleGoal,
    ExpandCastleGoal,
    TrainWorkerGoal,
    BuildFarmGoal,
    BuildHouseGoal,
    BuildLumbermillGoal,
    BuildMarketGoal,
    BuildMineGoal,
    MarketTradeGoal,
)
from .military import (
    BuildBarracksGoal,
    BuildStableGoal,
    BuildTempleGoal,
    BuildBlacksmithGoal,
    BuildSiegeWorkshopGoal,
    BuildWatchtowerGoal,
    TrainWarriorGoal,
    TrainArcherGoal,
    TrainSpearmanGoal,
    TrainCavalryGoal,
    TrainHorseArcherGoal,
    TrainAxemanGoal,
    TrainHealerGoal,
    TrainRamGoal,
    ResearchImprovedToolsGoal,
    ResearchForgedBladesGoal,
    ResearchFletchingGoal,
    ResearchPaddedArmorGoal,
    ResearchReinforcedFramesGoal,
    ResearchSiegeEngineeringGoal,
)
from .tactical import (
    DefendBaseGoal,
    AttackGoal,
    ControlFountainGoal,
    ScoutGoal,
)


from .ages import AdvanceAgeGoal, UpgradeUnitLineGoal, PrepareAgeGoal

ALL_GOALS = [
    TrainClosingPackageGoal,
    AdvanceAgeGoal,
    PrepareAgeGoal,
    UpgradeUnitLineGoal,
    # Tactical first — DefendBase has the highest possible scores
    DefendBaseGoal,
    AttackGoal,
    ControlFountainGoal,
    ScoutGoal,
    # Military structures and training
    BuildBarracksGoal,
    BuildStableGoal,
    BuildTempleGoal,
    BuildBlacksmithGoal,
    BuildSiegeWorkshopGoal,
    BuildWatchtowerGoal,
    TrainWarriorGoal,
    TrainArcherGoal,
    TrainSpearmanGoal,
    TrainCavalryGoal,
    TrainHorseArcherGoal,
    TrainAxemanGoal,
    TrainHealerGoal,
    TrainRamGoal,
    ResearchImprovedToolsGoal,
    ResearchForgedBladesGoal,
    ResearchFletchingGoal,
    ResearchPaddedArmorGoal,
    ResearchReinforcedFramesGoal,
    ResearchSiegeEngineeringGoal,
    # Economy
    RebuildCastleGoal,
    ExpandCastleGoal,
    MarketTradeGoal,
    TrainWorkerGoal,
    BuildHouseGoal,
    BuildFarmGoal,
    BuildLumbermillGoal,
    BuildMineGoal,
    BuildMarketGoal,
]
