from .economy import (
    RebuildCastleGoal,
    TrainWorkerGoal,
    BuildFarmGoal,
    BuildHouseGoal,
    BuildLumbermillGoal,
    BuildMarketGoal,
    BuildMineGoal,
    BuildQuarryGoal,
    MarketTradeGoal,
)
from .military import (
    BuildBarracksGoal,
    BuildStableGoal,
    BuildBlacksmithGoal,
    BuildSiegeWorkshopGoal,
    BuildWatchtowerGoal,
    BuildWallGoal,
    TrainWarriorGoal,
    TrainArcherGoal,
    TrainSpearmanGoal,
    TrainCavalryGoal,
    TrainRamGoal,
    ResearchImprovedToolsGoal,
    ResearchForgedBladesGoal,
    ResearchFletchingGoal,
    ResearchPaddedArmorGoal,
    ResearchReinforcedFramesGoal,
    ResearchSiegeEngineeringGoal,
)
from .tactical import (
    DefendBaseGoal,
    AttackGoal,
    ScoutGoal,
)


ALL_GOALS = [
    # Tactical first — DefendBase has the highest possible scores
    DefendBaseGoal,
    AttackGoal,
    ScoutGoal,
    # Military structures and training
    BuildBarracksGoal,
    BuildStableGoal,
    BuildBlacksmithGoal,
    BuildSiegeWorkshopGoal,
    BuildWatchtowerGoal,
    BuildWallGoal,
    TrainWarriorGoal,
    TrainArcherGoal,
    TrainSpearmanGoal,
    TrainCavalryGoal,
    TrainRamGoal,
    ResearchImprovedToolsGoal,
    ResearchForgedBladesGoal,
    ResearchFletchingGoal,
    ResearchPaddedArmorGoal,
    ResearchReinforcedFramesGoal,
    ResearchSiegeEngineeringGoal,
    # Economy
    RebuildCastleGoal,
    MarketTradeGoal,
    TrainWorkerGoal,
    BuildHouseGoal,
    BuildFarmGoal,
    BuildLumbermillGoal,
    BuildMineGoal,
    BuildQuarryGoal,
    BuildMarketGoal,
]
